### ISSUE TITLE
No Connection Adapters [?]

### ISSUE THREAD

**Issue by RHQ-Rusty** [xanthe1337/Hwid-Auth-Verify#1]
```
MY_PATH_TO_FILE>python webapprequest.py
Traceback (most recent call last):
  File "webapprequest.py", line 17, in <module>
    isAuth = Auth()
  File "webapprequest.py", line 10, in Auth
    r = requests.get(f'localhost:8083/backend?hwid={hwid}')
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'localhost:8083/backend?hwid=MY_HWID'
```

Obviously, `MY_HWID` is legitimately my UUID, and `MY_PATH_TO_FILE` is actually my path; they've just been censored for security. Why is this happening?

**Comment by xanthe1337** [comment]
`r = requests.get('localhost:8083?hwid={hwid}')` not a real url, am i wrong?

**Comment by RHQ-Rusty** [comment]
I meant to update it @xanthe1337 - I have http:// in the URL working, but when I make https:// requests, I get this error:
![image](https://user-images.githubusercontent.com/42674949/79075531-6a2ba900-7cc1-11ea-9ace-69b5b95cc8c1.png)

Here is the console's log:
![image](https://user-images.githubusercontent.com/42674949/79075539-7879c500-7cc1-11ea-974a-910fbb042724.png)

**Comment by xanthe1337** [comment]
Umm, i'm not sure, maybe it just doesn't support `https://`?
